### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/website-spyder#109]
* [ ] I think the open collective icon is too big. On High DPI screens it looks pixelated. Maybe use an SVG instead of a png?

* [x] I think the footer would look better in a dark color with white icons and text, to generate a more clearer separation of concerns.

* [x] I think having so many attributions clouds a bit the footer. We could use that real state for more meaningfull information and have all those attributions on a separate page with more details.

  Template © 2016 Free HTML5 OTemplate. Some rights reserved; licensed CC-BY 3.0.
  Designed by FreeHTML5.co Demo Images: Pexels
  Icons by Freepik from www.flaticon.com are licensed CC 3.0 BY
  Hugo port by SteveLane
  Lektor port by Dalthviz

* [ ] The plugin images should be more homogeneous, it seems the screenshots were taken on different versions of spyder on different Operating systems.

**Comment by CAM-Gerlach** [comment]
> On High DPI screens it looks pixelated. 

Indeed; it does if examined closely even on my normal DPI screen.

>  I think the footer would look better in a dark color with white icons and text, 

I dunno about this one; I'd have to see it on ``develop``. It looks pretty clear right now at least to me with the horizontal rule and drop shadow, and making it too dark might lend it too much weight and look out of place with the otherwise light and clean theme of the rest of the page.

>  I think having so many attributions clouds a bit the footer.

Agreed, and they are rather inconsistent in their wording between themselves. There's also a random line break in the first one for no reason as well as way too much line spacing, making the situation even worse, and overall there's way too much white space especially below the footer text.

>  The plugin images should be more homogeneous

Yeah, I guess—they should all be with a modern Spyder/OS/plugin version, but variety in OS, etc. is a good thing in that context, as they need to be visually distinct and it also demonstrates that they run on multiple platforms. I suppose the bigger issue is the plugins are unsupported right now, and some of them don't even work. Furthermore, they *still* link to just slightly larger versions of the images themselves, when obviously they should of course be linking to the actual plugin pages (I raised this issue before).

**Comment by CAM-Gerlach** [comment]
@goanpeca Edited your post to make it a checklist for clarity and so we can indicate completion; hope you don't mind and please edit further if desired.

**Comment by dalthviz** [comment]
I think the open collective icon is already and `SVG`

**Comment by CAM-Gerlach** [comment]
Yup, I checked it as well.

**Comment by goanpeca** [comment]
@dalthviz could we close this now ?

**Comment by dalthviz** [comment]
Um I guess so :+1:
