### ISSUE TITLE
Remove Blog link in blog navbar

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/website-spyder#133]
This is similar to the issue I opened in spyder-docs: right now you can see

    Home Blog Docs

in the blog navbar, but it should show instead

    Home Docs

@dalthviz, please work on this one.

**Comment by CAM-Gerlach** [comment]
As a general comment on this line of action, an (possibly more idiomatic and cohesive) alternative is to have the Spyder word mark top left link to the homepage, and then indicate the sub-section (home, blog, docs, etc) by both the title (or other such element) in the page content area, as well as the section name in the top bar (e.g. BLOG) shown as active (in our UI, darker). This tends to be a much more common paradigm outside of the OSS world where the whole site tends to be more cohesive vs. several modular sub-projects (main, blog, docs, etc). Essentially, we'd keep the top right section selection the same as it is now (and the same across all pages/sub-sites), and make the top left graphic the standard Spyder logo + word mark (as on the main page) on all pages.

Likely advantages of an approach with a common left-graphic and right-section navbar across all site sections (main, blog, docs, FAQ, future pages, etc.), include:

* Scales better: Easier to create new pages/sections with less overhead of creating a custom graphic and navbar
* Consistent header and navigation for users across site, making it more cohesive
* Conforms to more common UI paradigm (click logo to return to homepage; click section headers to go to section homepages)
* ``Home`` can be eliminated from the common top-right navbar, making it shorter, rather than each individual page

Disadvantages:

* Requires some minimal additional work up front (reverting spyder-ide/spyder-docs#65 , eliminating home from the common top-right navbar and switching the top-left logos to the common homepage one) over this proposal
* Checking the current section/sub-site and going to its index page is a little less obvious (the former can be mostly mitigated by simply including a page title)

**Comment by CAM-Gerlach** [comment]
I'll take that as a no? I personally favor the alternative presented, but its not a big deal either way and we can always implement it later as our needs grow. :)

**Comment by ccordoba12** [comment]
> I'll take that as a no?

Only if you want to implement it. Else we'll move on as planned.

**Comment by CAM-Gerlach** [comment]
Since it seems very straightforward to implement it even for a newbie like me, I can work it into my schedule if there is a good chance you think you'd accept it. If not, then I don't want to trouble you further about it.

**Comment by ccordoba12** [comment]
I'd have to see it implemented to tell you if I like or not.
