### ISSUE TITLE
Add Instagram Link to footer in website 

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/website-spyder#156]
Please @dalthviz add the link to instagram account http://instagram.com/spyderide

**Comment by CAM-Gerlach** [comment]
Just add ``footer_instagram=https://instagram.com/spyderide`` to the `.lektorproject` file, since it already exists hardcoded in the theme. (BTW, once I upgrade the Spyder site to Lektor-Icon v2 instead of the legacy version in use now, you'll be able to customize the link text and add custom links to any arbitrary site from the config file.) And don't forget to always use HTTPS links for security and better SEO.
