### ISSUE TITLE
Website title

### ISSUE THREAD

**Issue by gwerbin** [spyder-ide/website-spyder#165]
The source for https://spyder-ide.org contains this:

```html
<title> Spyder Website</title>
```
but it should probably contain
```html
<title>Spyder IDE</title>
```
Putting the word "Website" in the title of the website is somewhat of a faux pas, in that it makes the website feel outdated and goofy. It's especially out of place on a polished, modern website like the current homepage.

It looks like the correct place to make the change is here: https://github.com/spyder-ide/website-spyder/blob/183fbfd8268880221876494451d6006c8995ef22/spyder_website.lektorproject#L2

Also, there is a stray space character in the title element, which might be a bug in Lektor.

**Comment by goanpeca** [comment]
Thanks for the feedback @gwerbin.

Would you be interested in making a PR to correct this?

Thanks!

**Comment by CAM-Gerlach** [comment]
@gwerbin Great point, thanks. If you want to do the honors with a PR to get credit for the fix, that would be splendid; otherwise we can take care of it. The bug would be in the theme, not in Lektor, and is fixed in my overhauled version; we'll pick up the improvement for free once we port the site over.

**Comment by gwerbin** [comment]
Hi, sorry I never followed up on this. Should I still make a PR with the name change?

**Comment by ccordoba12** [comment]
Yes, please do.
