### ISSUE TITLE
Change blog text in blog website to home

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/website-spyder#182]

**Comment by isabela-pf** [comment]
I was looking at the docs the other day and I think I may have made a mistake in advising about the navigation between the main Spyder page, the docs, and the blog. Because the navigation has some differences in UI, I thought each one was more separate from each other than they actually are. Looking a little closer made me realize they seem to be the same site. This is absolutely my misunderstanding.

The reason this matters is because when I was talking about changing the navigation titles to the right (usually Docs or Blog) to be Home for which ever part of the site we were on. My thought was “If I’m on the docs website, then clicking something that says Docs sounds like I’m not already there, and it will be confusing to see nothing changing. It should be home because it is the docs’ home.” But trying it out now that I’ve realized it feels weird since there is a true home. 

I do think keeping the Spyder logo linked back to the main Spyder page (the true home) makes sense still.
I think what would be more helpful to change than the name (as has already been done on the docs, but not the blog or main page yet) is to have some kind of indicator which main section of the website the user is on to avoid the confusion I mentioned above. It could be as simple as underlining the title (2px tall!) like this.

<img width="1152" alt="Proposed Highlight 1" src="https://user-images.githubusercontent.com/50221806/99863114-88a82b80-2b51-11eb-8e8b-c0491dd7c760.png">
<img width="1153" alt="Proposed Highlight 2" src="https://user-images.githubusercontent.com/50221806/99863117-89d95880-2b51-11eb-8741-dcdadac981ab.png">

Once again, sorry since this was absolutely my mistake. I still wanted to follow up since I don’t want to misguide.

**Comment by CAM-Gerlach** [comment]
Thanks @isabela-pf . Implemented exactly as suggested above in spyder-ide/lektor-icon#16 . Also, made the underline smoothly transition to indicate the current homepage/singlepage section the user is currently on, as the original theme did. Since the changes are a clear improvement, making the current page and section clearer and consistent with each other, and pick up their colors and styling cues from the existing theme while taking advantage of the new theme functionality, I just made the style changes theme-side as well, so all we'll need site-side is a bump to the theme submodule commit, unless we want further style customization (which is perfectly possible following the theme-side changes, so long as we decide on what we want).

Its a simple matter to apply this to the docs navbar as well so they are all consistent, cohesive and have a unique look across the sub-sections of the site; I can do that along with a fix so the docs navbar has the same height as the site one (it never matched from the beginning), as well as tweak the text opacity so it matches the higher-contrast, easier to read version we decided on for the rest of the site. Just lmk.

**Comment by CAM-Gerlach** [comment]
> Its a simple matter to apply this to the docs navbar as well so they are all consistent, cohesive and have a unique look across the sub-sections of the site; [...]

Implemented all as spyder-ide/spyder-docs-sphinx-theme#39

**Comment by juanis2112** [comment]
From the docs meeting, we will have it like this but when a person is in a subpage of the blog or the docs, the text should not be underlined. Also we will add a title on the top page of the blog that say "Welcome to Spyder's Blog"

**Comment by CAM-Gerlach** [comment]
Updated both PRs accordingly
