### ISSUE TITLE
Your homepage doesn't have a download button

### ISSUE THREAD

**Issue by gernophil** [spyder-ide/website-spyder#219]
see https://www.spyder-ide.org/#section-download

**Comment by ccordoba12** [comment]
Hey @gernophil, thanks for reporting. I guess you're referring to our Linux installer, right? Well, that's marked as experimental for Spyder 5:

https://github.com/spyder-ide/spyder/releases/tag/v5.5.0

That's why we don't promote in our webpage.

However, it'll be our default method of installation in Spyder 6, to be released in two or three months, and then we'll show a link for it in our webpage.

To not forget to do that, I'll move this issue to our website repository.

**Comment by gernophil** [comment]
Hey @ccordoba12,

Actually, I am referring to the macOS standalone, but this is platform independent. You write on your HP:

"Click the button below to download the suggested installer for your platform."

However, there is not download button for any OS. Only if you click the link to the full installation instructions, there is a download link somewhere on the docs page. I am pretty sure buttons have been there before and I tested multiple browsers.

**Comment by ccordoba12** [comment]
Then I guess you have an M1 Mac? In that case our mechanism to detect your OS and suggest the appropriate installer for it could be the problem.

**Comment by gernophil** [comment]
Ah, yes. That might be the case. I have an M1. I'll double check with a windows machine later.

**Comment by gernophil** [comment]
I just checked from a Windows PC using Edge and Firefox. Both don't show a download button or am I just to blind to see it?

**Comment by ccordoba12** [comment]
You're totally right. The download button vanished from our webpage! Thanks for letting us know about it.

We'll take a look at that next week.

**Comment by gernophil** [comment]
Happy to help :). Have a nice weekend.

**Comment by ccordoba12** [comment]
You too @gernophil!

**Comment by CAM-Gerlach** [comment]
Sorry about this, and thanks for reporting! This was a bug introduced by an unexpected interaction as a result of the minor theme update that was (my mistake) included in #218 , specifically no longer allowing the nesting of `mutlisection` flowblock sections on the main page to be nested inside other `mutlisection` flowblocks, which due to a bug in Lektor resulted in a recursion error attempting to load the admin panel GUI.

While this capability wasn't actually needed by the Spyder website at present and no error was reported in testing, a vestigial nested `multisection` was in fact still present due to the Download section formerly containing multiple download buttons as well as a content flowblock (before displaying the correct button for the current OS was handled by a script), which resulted in the section containing the button silently being dropped.

In any case, I've opened PR #220 to fix this by removing the vestigial nested `multisection`, and will explore reporting both issues (the recursion error in the admin panel, and the nested mutlisection being silently dropped with no warning) upstream to Lektor. Thanks again!
