### ISSUE TITLE
Add a Frequently Asked Questions section

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/website-spyder#61]
Many users run into the same mistakes, or have similar questions:

- %matplotlib inline
-  %gui tk
- qtpy.PythonQtError: No Qt bindings could be found
- discouraging mixing conda with pip (or different conda channels)

**Comment by ccordoba12** [comment]
This is a nice idea. @CAM-Gerlach, could you help us with it?

**Comment by CAM-Gerlach** [comment]
I can do the writing, but I'll need some sort of page skeleton to get me started, since ``lektor`` doesn't seem to want to render the site remotely properly locally so I have no way to really develop and test anything layout based, and I haven't worked very much at all in CSS/etc. to go on. Also, this is another case where it would be helpful to have somewhere to test how the changes look and tweak accordingly before pushing to production, in order to enable rapid iteration and minimal disruption of the existing page. I'd think to make it a separate page like the blog, and should have some sort of table of the questions at the top/side with at least one level of categories and links to the questions down the page, kind of like the links on the current homepage.

On the content side, definitely send any ideas for common questions my way, and I'd be curious how you'd like the scope of this to diverge from that of the Troubleshooting Guide—I'm thinking more "What Spyder is/isn't|can/can't do" and beginner "How do I?" questions vs. troubleshooting/known issues type stuff, but a few basic install questions like those mentioned above could be okay while mainly relying on links to the Troubleshooting Guide for anything further.

**Comment by ccordoba12** [comment]
> I can do the writing, but I'll need some sort of page skeleton to get me started

You can do that in Dropbox Paper for now. When we finish the frontpage, @dalthviz can create an skeleton for you.

> Also, this is another case where it would be helpful to have somewhere to test how the changes look and tweak accordingly before pushing to production

Sure, but we depend on @goanpeca for that.

> I'd think to make it a separate page like the blog, and should have some sort of table of the questions at the top/side with at least one level of categories and links to the questions down the page, kind of like the links on the current homepage.

Yep, good idea.

> I'm thinking more "What Spyder is/isn't|can/can't do" and beginner "How do I?" questions

That sound like a good plan.

**Comment by CAM-Gerlach** [comment]
> You can do that in Dropbox Paper for now. When we finish the frontpage, @dalthviz can create an skeleton for you.

Okay, will do. Right now in the queue its behind the front page copyedit/etc., baseline copyediting/updating the docs for the initial release, and the legal stuff needed for numfocus etc and then finishing that proposal itself (and I'm going to need to work on a bunch of term projects at some point...), but I can bump it up if desired. After May 1 I should have more time for everything though I'll be trying to get those priority items done ASAP.

**Comment by ccordoba12** [comment]
> After May 1 I should have more time for everything though I'll be trying to get those priority items done ASAP.

Ok, thanks for all your help! Don't worry too much about this one, it's not critical.

**Comment by goanpeca** [comment]
Doing some cleaning up on issues.

@ccordoba12 do we want to have a `develop`site and a `production` site so these changes can be tested before official publishing? (should be straightforward to setup)

**Comment by CAM-Gerlach** [comment]
@goanpeca [We already do](http://develop.spyder-ide.org/) lol, you yourself were the one that set that up jeje.

**Comment by goanpeca** [comment]
Oops hehe, so I guess teh question is if you would like to help with the FAQ :-) ?

**Comment by CAM-Gerlach** [comment]
Sure, I could do it, though @ccordoba12 getting me started with a list of some current questions would be helpful. We could just use a normal page like I did for the [FAQ](https://www.star-fleet.tours/faq/) on the [Star Fleet site](https://www.star-fleet.tours/) (based, of course, on the rewrite of Lektor-Icon), though I'd like to add a custom template/model with things like expanding/collapsing questions and maybe even an index at some point, if I ever get the time.

**Comment by CAM-Gerlach** [comment]
Added to the docs in spyder-ide/spyder-docs#174
