### ISSUE TITLE
Improve text of the front page

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/website-spyder#99]
The text present in the various sections and subsections of the front page needs several improvements. @CAM-Gerlach said he's going to help us with that.

@CAM-Gerlach, please make this your priority along with the screenshots for Spyder components.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 After two marathon screenshotting sessions I finally have everything we need (nearly 200 in all), way overkill to update our current docs but designed to provide comprehensive coverage for everything we'll want in the greatly expanded mega-overhaul that I'll hopefully be able to complete this summer. Therefore, now on to the site.

What's there at this point isn't bad (a good amount of it now appears to be based on existing contentI've copyedited already); there just isn't much of it. Aside from a copyedit pass on the existing text which I can do fairly quickly, what specifically are you looking for me to add/expand?

**Comment by ccordoba12** [comment]
> After two marathon screenshotting sessions I finally have everything we need (nearly 200 in all)

Gee, that's a lot! Please select one for each component present in the *Components* section and upload it here. I plan to create a gallery view (similar to the one in *Plugins*) when users click on any component icon with them.

> Aside from a copyedit pass on the existing text which I can do fairly quickly, what specifically are you looking for me to add/expand?

Please take a look at our grammar and syntax. Also, if the wording or tone of a section can be improved, please do it too. This shouldn't take you more than an hour, hopefully.

**Comment by CAM-Gerlach** [comment]
> Gee, that's a lot!

Yeah, at least one for each and every integral UI element—panel, menu, context-menu, toolbar, pref pane, editor feature, dialog, variable editor, and popup. For each pane/component/major interface element, I have one ``standard`` screenshot showcasing the default look/features, plus potentially a number of others showcasing specific/alternate usage.

> Please select one for each component present in the Components section and upload it here.

To e.g. ``content/components``? There's also a whole directory tree of the same mostly out of date images from the doc; should I just update all that directly with the ``standard`` ones for each component clearly marked as they are, and so they're all these for future use as necessary (since all the out of date doc ones are there anyway)? Or should the latter just be removed?

> Please take a look at our grammar and syntax. Also, if the wording or tone of a section can be improved, please do it too. This shouldn't take you more than an hour, hopefully.

Oh okay, then that should be really quick since with the recent changes it is actually pretty decent to start with. I'll take a shot at it now; thanks for clarifying.
